### ISSUE TITLE
PDF Issue

### ISSUE THREAD

**Issue by enricobottazzi** [lmarzocchetti/mangaworld_downloader#1]
I had a problem in installing the `img2pdf`. 

```
Building wheels for collected packages: pikepdf
  Building wheel for pikepdf (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pikepdf (pyproject.toml) did not run successfully.
```

I don't know if it's only me. Anyway, I replaced the package with another one in my fork. If you are interested in merging, I can create a PR

**Comment by lmarzocchetti** [comment]
Forse si sarà rotta questa dipendenza visto che lo script l'ho scritto con python 3.9 se non ricordo male. Comunque accetto pull request, solo che in questo momento non sono a casa. Torno fra qualche giorno, nel frattempo se vuoi fare una pull request io poi testo tutto, oppure lasciami un contatto e ci sentiamo

**Comment by enricobottazzi** [comment]
Ok! Creata #3
